export default {
  HTTP_REQUEST_INIT: "HTTP_REQUEST_INIT",
  HTTP_REQUEST_SUCCESS: "HTTP_REQUEST_SUCCESS",
  HTTP_REQUEST_ERROR: "HTTP_REQUEST_ERROR",
  LATEST_RATES_SUCCESS: "LATEST_RATES_SUCCESS",
  ADD_CARD: "ADD_CARD",
  UPDATE_CARD: "UPDATE_CARD",
  DELETE_CARD: "DELETE_CARD",
  DELETE_ALL_CARDS: "DELETE_ALL_CARDS",
  FLIP_CARD: "FLIP_CARD"
};
